version: '3.8'

services:
  neo4j:
    image: neo4j:5.20.0  # You can change to the latest stable version if needed
    container_name: neo4j
    ports:
      - 7474:7474   # Browser UI
      - 7687:7687   # Bolt protocol (used by drivers)
    environment:
      NEO4J_AUTH: neo4j/test1234  # username: neo4j, password: test123
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
