services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    entrypoint: ["qdrant"]        # explicitly invoke the qdrant binary
    command:
      - "--storage.storage_path"
      - "/qdrant/storage"

volumes:
  qdrant_data:
